'use client'

// Teacher classroom home (plan phase 2): the list of classes a teacher owns,
// each with its join code + invite link, plus a tile to create a new class.
// Teacher-only — students/standard accounts are redirected to /dashboard.

import { useCallback, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import { DashboardHeader } from '@/components/dashboard/DashboardHeader'
import { ClassCard, CreateClassCard } from '@/components/classroom/ClassCard'
import Footer from '@/components/sections/Footer'
import { capabilitiesFor } from '@/lib/auth/capabilities'
import type { AccountType } from '@/lib/profile/data'
import { rowToClass, type ClassRow, type ClassSummary } from '@/lib/classroom/classes'

const CLASS_COLUMNS = 'id, name, join_code, created_at'

// Full-height via the dvh-safe .acct-vh-min class (account-responsive.css).
const centerNotice: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  background: 'var(--parchment)',
  fontFamily: 'var(--font-mono)',
  fontSize: 11,
  letterSpacing: '0.11em',
  textTransform: 'uppercase',
  color: 'var(--ink-subtle)',
}

export default function ClassroomPage() {
  const router = useRouter()
  const [classes, setClasses] = useState<ClassSummary[] | null>(null)
  const [counts, setCounts] = useState<Record<string, number>>({})
  const [newName, setNewName] = useState('')
  const [creating, setCreating] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const load = useCallback(async () => {
    const supabase = createClient()
    const {
      data: { user },
    } = await supabase.auth.getUser()
    if (!user) {
      router.replace('/login')
      return
    }

    // Teacher-only gate (capabilities.ts is the single source of truth).
    const { data: profile } = await supabase.from('profiles').select('account_type').eq('id', user.id).single()
    if (!capabilitiesFor((profile?.account_type as AccountType) ?? 'standard').canCreateClasses) {
      router.replace('/dashboard')
      return
    }

    const { data, error } = await supabase
      .from('classes')
      .select(CLASS_COLUMNS)
      .eq('teacher_id', user.id)
      .order('created_at', { ascending: false })
    if (error) {
      setError('Could not load your classes. Please refresh.')
      setClasses([])
      return
    }
    const list = (data as ClassRow[]).map(rowToClass)
    setClasses(list)

    // Roster sizes: one query, tallied client-side (RLS lets a teacher read the
    // member rows of their own classes).
    if (list.length > 0) {
      const { data: members } = await supabase
        .from('class_members')
        .select('class_id')
        .in('class_id', list.map((c) => c.id))
      const tally: Record<string, number> = {}
      for (const m of (members as { class_id: string }[]) ?? []) {
        tally[m.class_id] = (tally[m.class_id] ?? 0) + 1
      }
      setCounts(tally)
    }
    setError(null)
  }, [router])

  useEffect(() => {
    load()
  }, [load])

  async function handleCreate() {
    const name = newName.trim()
    if (!name || creating) return
    setCreating(true)
    const supabase = createClient()
    const {
      data: { user },
    } = await supabase.auth.getUser()
    if (!user) {
      router.replace('/login')
      return
    }
    // join_code is auto-generated by the DB default (migration 0014).
    const { error } = await supabase.from('classes').insert({ teacher_id: user.id, name })
    setCreating(false)
    if (error) {
      setError('Could not create the class. Please try again.')
      return
    }
    setNewName('')
    load()
  }

  async function handleSignOut() {
    const supabase = createClient()
    await supabase.auth.signOut()
    router.push('/login')
    router.refresh()
  }

  if (classes === null) {
    return <main id="main" className="acct-vh-min" style={centerNotice}>Loading your classroom…</main>
  }

  return (
    <div className="acct-vh-min" style={{ display: 'flex', flexDirection: 'column', background: 'var(--parchment)' }}>
      <DashboardHeader onSignOut={handleSignOut} showClassroom active="classroom" />

      <main style={{ flex: '1 1 auto' }}>
        <div className="container" style={{ paddingBlock: 'clamp(32px, 5vw, 56px)' }}>
          <h1 style={{ fontFamily: 'var(--font-display)', fontWeight: 500, fontSize: 'clamp(30px, 4vw, 40px)', letterSpacing: '-0.015em', color: 'var(--ink)' }}>
            Your Classroom
          </h1>
          <p style={{ fontFamily: 'var(--font-body)', fontSize: 16, color: 'var(--ink-mid)', marginTop: 8 }}>
            Create a class, share its join code, and follow your students&apos; houses.
          </p>

          {error && (
            <p className="mono" style={{ fontSize: 11, color: 'var(--warning-text)', marginTop: 16 }}>
              {error}
            </p>
          )}

          <div
            className="acct-card-grid"
            style={{
              display: 'grid',
              gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
              gap: 20,
              marginTop: 'clamp(24px, 3vw, 36px)',
            }}
          >
            {classes.map((c) => (
              <ClassCard key={c.id} cls={c} memberCount={counts[c.id] ?? 0} />
            ))}
            <CreateClassCard value={newName} onChange={setNewName} onCreate={handleCreate} disabled={creating} />
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
